# -*- coding: utf-8 -*-

BOT_NAME = 'tabelog'

SPIDER_MODULES = ['tabelog.spiders']
NEWSPIDER_MODULE = 'tabelog.spiders'
USER_AGENT = 'ITAM'

DEPTH_LIMIT = 0
LOG_LEVEL = 'INFO'
ROBOTSTXT_OBEY = True
# CONCURRENT_REQUESTS = 32
AUTOTHROTTLE_DEBUG = False
AUTOTHROTTLE_ENABLED = True
# AUTOTHROTTLE_MAX_DELAY = 60
# AUTOTHROTTLE_START_DELAY = 5
# AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
